vich_uploader:
    db_driver: orm

    mappings:
       docs:
            uri_prefix: /images/docs
            upload_destination: '%kernel.project_dir%/public/images/docs'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
